version: "3"

services:
  web:
    build: .
    container_name: kamu-tau-cara-debug
    command: python /code/manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/code
    ports:
      - 9150:8080
